name: bfgn
channels:
  - defaults
  - conda-forge
dependencies:
  - black>=19.3b0
  - pydocstyle>=3.0.0
  - pytest>=4.6.2
  - pytest-cov>=2.7.1
  - pytest-xdist>=1.29.0
  - python=3.7.3
  - tox>=3.14.0
