raw_files:
  feature_files: REQUIRED
  response_files: REQUIRED
  boundary_files: OPTIONAL
  feature_data_type: REQUIRED
  response_data_type: REQUIRED
  feature_nodata_value: -9999.0
  response_nodata_value: -9999.0
  boundary_bad_value: OPTIONAL
  ignore_projections: false
data_build:
  dir_out: .
  log_level: INFO
  filename_prefix_out: ''
  network_category: FCN
  random_seed: 1
  max_samples: REQUIRED
  max_built_data_gb: 10.0
  number_folds: 10
  validation_fold: 0
  test_fold: OPTIONAL
  window_radius: REQUIRED
  loss_window_radius: REQUIRED
  feature_mean_centering: false
  feature_nodata_maximum_fraction: 0.0
  response_min_value: OPTIONAL
  response_max_value: OPTIONAL
  response_background_values: OPTIONAL
  sample_spacing: OPTIONAL
data_samples:
  apply_random_transformations: false
  batch_size: 100
  feature_scaler_names: REQUIRED
  response_scaler_names: REQUIRED
  feature_nodata_encoding: -10.0
model_training:
  dir_out: .
  log_level: INFO
  verbosity: 1
  assert_gpu: false
  architecture_name: flat_net
  loss_metric: REQUIRED
  max_epochs: 100
  optimizer: adam
  weighted: false
architecture:
  filters: REQUIRED
  internal_activation: relu
  kernel_size: [3, 3]
  n_classes: REQUIRED
  num_layers: 8
  output_activation: REQUIRED
  padding: same
  use_batch_norm: false
  use_initial_colorspace_transformation_layer: false
model_reporting:
  max_pages_per_figure: 1
  max_samples_per_page: 20
  max_features_per_page: 10
  max_responses_per_page: 10
  network_progression_max_pages: 1
  network_progression_max_filters: 10
  network_progression_show_full: true
  network_progression_show_compact: true
callback_general:
  checkpoint_periods: 5
  use_terminate_on_nan: true
callback_tensorboard:
  use_callback: true
  update_freq: epoch
  histogram_freq: 0
  write_graph: true
  write_grads: false
  write_images: true
callback_early_stopping:
  use_callback: true
  loss_metric: val_loss
  min_delta: 0.0001
  patience: 10
callback_reduced_learning_rate:
  use_callback: true
  factor: 0.5
  loss_metric: val_loss
  min_delta: 0.0001
  patience: 5
